# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_form',
            old_name='Project_progress',
            new_name='Progress',
        ),
    ]
