# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0002_auto_20180425_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_form',
            old_name='Progress',
            new_name='Project_progress',
        ),
    ]
