# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0003_auto_20180425_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_form',
            name='Project_progress',
        ),
        migrations.DeleteModel(
            name='Project_progress',
        ),
    ]
