# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0004_auto_20180425_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_form',
            name='project_progress',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed'), ('Just Started', 'Just Started'), ('Half Cooked', 'Half Cooked')], default='', max_length=48),
            preserve_default=False,
        ),
    ]
